spring.datasource.url=jdbc:postgresql://${DB_HOST_18}:${DB18_PORT}/${DB18_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect


spring.jpa.hibernate.ddl-auto=update
# diz o que esta sendo feito no banco de dados, a jpa faz ele mostra
spring.jpa.show-sql=true
# para ver tudo formatado
spring.jpa.format-sql=true