spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Define o dialeto do Hibernate para PostgreSQL (ajuda o Hibernate a gerar SQL correto para esse banco)

spring.datasource.driver-class-name=org.postgresql.Driver
# Informa qual driver Java será usado para conectar ao PostgreSQL

spring.datasource.username=postgres
# Usuário do banco de dados (login)

spring.datasource.password=@Idel140211
# Senha do banco de dados

spring.datasource.url=jdbc:postgresql://localhost:5432/MeuBancoTest
# Endereço de conexão com o banco:
# localhost = computador local
# 5432 = porta padrão do PostgreSQL
# meubanco = nome do banco

spring.jpa.generate-ddl=true
# Permite que o JPA gere automaticamente as tabelas no banco

spring.jpa.hibernate.ddl-auto=update
# Define como o Hibernate vai lidar com o banco:
# update = atualiza tabelas sem apagar dados

spring.jpa.show-sql=true
# Mostra no console os comandos SQL que o Hibernate executa
